docker_packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - lsb-release
docker_gpg_key_url: https://download.docker.com/linux/ubuntu/gpg
docker_repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
docker_package: docker-ce
docker_service: docker
docker_user: azureuser
