java_version: openjdk-17-jdk
sonarqube_user: sonarqube
sonarqube_zip_url: https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-10.3.0.82913.zip
sonarqube_zip_dest: /tmp/sonarqube.zip
sonarqube_extract_dest: /opt/
sonarqube_dir: /opt/sonarqube
sonarqube_service_file: /etc/systemd/system/sonarqube.service
sonarqube_service_content: |
  [Unit]
  Description=SonarQube service
  After=syslog.target network.target

  [Service]
  Type=forking
  ExecStart=/opt/sonarqube/bin/linux-x86-64/sonar.sh start
  ExecStop=/opt/sonarqube/bin/linux-x86-64/sonar.sh stop
  User=sonarqube
  Group=sonarqube
  Restart=always
  LimitNOFILE=65536
  LimitNPROC=4096

  [Install]
  WantedBy=multi-user.target
sonarqube_service: sonarqube
sonar_scanner_version: 4.9.3.744
sonar_scanner_zip_url: https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-{{ sonar_scanner_version }}-linux.zip
sonar_scanner_zip_dest: /tmp/sonar-scanner.zip
sonar_scanner_extract_dest: /opt/
sonar_scanner_extracted_dir: sonar-scanner-{{ sonar_scanner_version }}-linux
sonar_scanner_dir: /opt/sonar-scanner
